services:
  # Backend API D§
  - type: web
    name: edutext-pro-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://xrjrddwrsasjifhghzfl.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyanJkZHdyc2FzamlmaGdoemZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTg1NTIsImV4cCI6MjA2Nzk5NDU1Mn0.pAqrS-9NYXiUZ1lONXlDm8YK-c3zhZj2VIix0_Q36rw
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyanJkZHdyc2FzamlmaGdoemZsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjQxODU1MiwiZXhwIjoyMDY3OTk0NTUyfQ.r3X0g1-J7zxDP9sxE7DYiW_o2_78qMbVfdsqEYahd-c
      - key: API_KEY_ENCRYPTION_SECRET
        value: EduTextPro2024SecretKey!@#$%^&*()1234567890
      - key: JWT_SECRET
        value: EduTextProJWTSecret2024!@#$%^&*()
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - key: CLAUDE_API_KEY
        value: your_claude_api_key_here

  # `∏‘‹  ¨t∏  
  - type: static
    name: edutext-pro-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production